config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, only: [:index, :new, :create], shallow: true do
    resources :likes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :likes, dependent: :destroy
	belongs_to :user

	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
		like = Like.new(user_id: current_user.id, post_id: params[:post_id])
		@post = like.post
		like.save
  end

  def destroy
		like = Like.find(params[:id])
		@post = like.post
		like.destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
  	@post.save
  	redirect_to posts_path
  end

  private

  def post_params
  	params.require(:post).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
$("#like-<%= @post.id %>").html("<%= j(render 'posts/like', post: @post) %>");

app/views/likes/destroy.js.erb
$("#like-<%= @post.id %>").html("<%= j(render 'posts/like', post: @post) %>");

app/views/posts/_like.html.erb
<% if post.liked_by?(current_user) %>
  <% like = Like.find_by(user_id: current_user.id, post_id: post.id) %>
  <%= link_to like_path(like), method: :delete, remote: true do %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;">
    <span><%= post.likes.count %></span>
  <% end %>
<% else %>
  <%= link_to post_likes_path(post), method: :post, remote: true do %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: gray;">
    <span><%= post.likes.count %></span>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<div class="container">
	<h1>記事一覧</h1>
	<table class="table">
		<% @posts.each do |post| %>
				<tr>
					<td><%= post.title %></td>
					<td id="like-<%= post.id %>">
						<%= render "like", post: post %>
					</td>
				</tr>
		<% end %>
	</table>
</div>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @post, local: true do |f| %>
	<%= f.text_field :title %>
	<%= f.submit "投稿" %>
<% end %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>